apiVersion: v1
kind: Service
metadata:
  name: passenger-service
spec:
  selector:
    app: passenger-service
  ports:
    - port: 8081
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: passenger-service
spec:
  selector:
    matchLabels:
      app: passenger-service
  template:
    metadata:
      labels:
        app: passenger-service
    spec:
      containers:
        - name: passenger-service
          image: tdeugdoer/passenger-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          resources:
            limits:
              memory: "500Mi"
              cpu: "0.7"