apiVersion: v1
kind: Service
metadata:
  name: rating-service
spec:
  selector:
    app: rating-service
  ports:
    - port: 8083
      targetPort: 8083
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-service
spec:
  selector:
    matchLabels:
      app: rating-service
  template:
    metadata:
      labels:
        app: rating-service
    spec:
      containers:
        - name: rating-service
          image: tdeugdoer/rating-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          resources:
            limits:
              memory: "300Mi"
              cpu: "0.5"