spring:
  application.name: rating-service
  cassandra:
    contact-points: cassandradb
    port: 9042
    keyspace-name: mykeyspace
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      properties:
        spring.json:
          trusted.packages: '*'
          type.mapping: RatingCreateEvent:com.tserashkevich.ratingservice.kafka.kafkaDtos.RatingCreateEvent
      group-id: group-1
      create-rating-topic:
        name: create-rating-topic

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1
    enabled: true

logging:
  level:
    root: INFO
  pattern:
    console: '{"timestamp":"%d{yyyy-MM-dd HH:mm:ss.SSS}", "level":"%p", "traceId":"%X{traceId}", "spanId":"%X{spanId}", "message":"%msg"}'

server:
  port: 8083