global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'passenger-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'passenger-service:8081' ]
  - job_name: 'driver-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'driver-service:8080' ]
  - job_name: 'ride-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'ride-service:8082' ]
  - job_name: 'rating-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'rating-service:8083' ]
  - job_name: 'kafka-exporter'
    scrape_interval: 45s
    scrape_timeout: 30s
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - 'host.docker.internal:9308'