spring:
  data:
    mongodb:
      uri: mongodb://mongodb/27017
      authentication-database: admin
      database: local
  kafka:
    bootstrap-servers: kafka:9092
  cloud:
    openfeign:
      client:
        config:
          geoapify:
            url: https://api.geoapify.com/v1
            connect-timeout: 3000
            read-timeout: 5000
          driver:
            url: http://driver-service:8080/api/v1/drivers
            connect-timeout: 3000
            read-timeout: 5000
          car:
            url: http://driver-service:8080/api/v1/cars
            connect-timeout: 3000
            read-timeout: 5000
          passenger:
            url: http://passenger-service:8081/api/v1/passengers
            connect-timeout: 3000
            read-timeout: 5000
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/taxi-aggregator
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/taxi-aggregator
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: passenger-service
            client-secret: mLpVyia4h1OPejq0ZDAHSdDpQDVc8Let
            scope: openid